# Generated by Django 2.0.6 on 2018-06-27 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staticpages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepage',
            options={'verbose_name': 'home page', 'verbose_name_plural': 'home pages'},
        ),
        migrations.AlterModelOptions(
            name='staticpage',
            options={'verbose_name': 'static page', 'verbose_name_plural': 'static pages'},
        ),
    ]
