# Generated by Django 2.0.6 on 2018-06-27 23:04

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandingPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('allow_signup', models.BooleanField(default=True, verbose_name='allow signup')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='landings', to='plans.Offer', verbose_name='offer')),
            ],
            options={
                'verbose_name': 'landing page',
                'verbose_name_plural': 'landing pages',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='LandingPageBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('heading', models.CharField(max_length=255, verbose_name='heading')),
                ('content', wagtail.core.fields.RichTextField()),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='landings.LandingPage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
