# Generated by Django 2.0.6 on 2018-06-27 10:02

from django.db import migrations, models
import django.db.models.deletion
import eightfit.apps.plans.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('discount', models.PositiveSmallIntegerField(default=0, verbose_name='discount')),
                ('price', eightfit.apps.plans.fields.PriceField(blank=True, help_text='Specify total price for offer. By default offer price is plan price - discount. You can manually set total price by specifying this field.', max_digits=8, null=True, verbose_name='price')),
                ('expire_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'offer',
                'verbose_name_plural': 'offers',
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='name')),
                ('stripe_plan', models.CharField(max_length=255, verbose_name='plan')),
                ('price', eightfit.apps.plans.fields.PriceField(max_digits=8, verbose_name='price')),
                ('currency', models.CharField(choices=[('eur', 'EUR'), ('usd', 'USD')], default='eur', max_length=8, verbose_name='currency')),
            ],
            options={
                'verbose_name': 'plan',
                'verbose_name_plural': 'plans',
            },
        ),
        migrations.AddField(
            model_name='offer',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offers', to='plans.Plan'),
        ),
    ]
